"""FastAPI entry point — mounts the MCP server, registers REST docs routes, and serves .pem key downloads."""

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response

load_dotenv()

from mcp_server import mcp
from docs_generator import register_mcp_docs_routes
from services.execution_service import get_key_file

_mcp_http_app = mcp.http_app(path="/")

app = FastAPI(
    title="Agentic Cloud Assistant — MCP API",
    description=(
        "AI-powered AWS management tool. "
        "Primary interface: POST /mcp (MCP protocol). "
        "These /tools/* endpoints are auto-generated from MCP tool schemas "
        "for testing and documentation purposes."
    ),
    version="2.0.0",
    lifespan=_mcp_http_app.lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["GET", "POST", "DELETE"],
    allow_headers=["*"],
    expose_headers=["mcp-session-id"],
)

app.mount("/mcp", _mcp_http_app)

register_mcp_docs_routes(app, mcp)


@app.get("/health", tags=["Health"], summary="Server uptime check")
def health():
    return {"status": "ok", "version": "2.0.0", "mcp_endpoint": "POST /mcp"}


@app.get(
    "/terraform/keys/{execution_id}/{filename}",
    tags=["Terraform"],
    summary="Download a .pem private key generated by a Terraform apply",
)
def download_key_file(execution_id: str, filename: str):
    """
    Binary file download — cannot be an MCP tool because MCP returns JSON only.
    This is the one endpoint that must remain as a real REST route.
    """
    try:
        key_bytes = get_key_file(execution_id, filename)
        return Response(
            content=key_bytes,
            media_type="application/x-pem-file",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "X-Content-Type-Options": "nosniff",
            },
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))


try:
    from rag.knowledge_base import knowledge_base as _knowledge_base
    _RAG_AVAILABLE = True
except Exception:
    _RAG_AVAILABLE = False


@app.post(
    "/rag/documents/upload",
    tags=["Knowledge Base"],
    summary="Upload a PDF or plain-text file to the ChromaDB knowledge base",
)
async def upload_rag_document(
    file: UploadFile = File(...),
    doc_id: str = Form(...),
    resource_type: str = Form("general"),
):
    """
    Multipart file upload — cannot be an MCP tool parameter because MCP is JSON-only.
    This mirrors the rag_upload_file MCP tool but accepts raw bytes via multipart/form-data.
    """
    if not _RAG_AVAILABLE:
        raise HTTPException(status_code=503, detail="RAG knowledge base is not available.")
    try:
        content = await file.read()
        if file.filename and file.filename.lower().endswith(".pdf"):
            import io
            import PyPDF2
            pdf_reader = PyPDF2.PdfReader(io.BytesIO(content))
            text = "\n\n".join(p.extract_text() or "" for p in pdf_reader.pages).strip()
        else:
            text = content.decode("utf-8", errors="ignore").strip()
        if not text:
            raise HTTPException(status_code=422, detail="No text could be extracted from the file.")
        result = _knowledge_base.add_document(
            doc_id=doc_id,
            text=text,
            metadata={"resource_type": resource_type, "filename": file.filename or ""},
        )
        return {"chunks_added": result.get("chunks_added", 0), "doc_id": doc_id}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn

    print("ACA backend starting on http://localhost:8000")
    print("  MCP endpoint : POST http://localhost:8000/mcp")
    print("  Swagger docs : http://localhost:8000/docs")
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
